In [4]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}

#Buat Series dari my_list


In [7]:
#ANSWER
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

#Buat Series dari my_list dengan menggunakan label


In [9]:
#ANSWER
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

#Buat Series dari arr dengan menggunakan label


In [11]:
#ANSWER
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int32

#Buat series dengan dictionary


In [13]:
#ANSWER
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [14]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'Germany', 'USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4], index = ['USA', 'Germany', 'Italia', 'Japan'])

USA        1
Germany    2
Italia     5
Japan      4
dtype: int64

In [15]:
#ANSWER
d1 = pd.Series(ser2)
d1

USA        1
Germany    2
Italia     5
Japan      4
dtype: int64

Germany    4.0
Italia     NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [16]:
#ANSWER
d2 = pd.Series(ser1)
d3 = d1 + d2
d3


Germany    4.0
Italia     NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

#Values Series 1

In [18]:
#ANSWER
d2.values

array([1, 2, 3, 4], dtype=int64)

In [19]:
#ANSWER
ser1.values

array([1, 2, 3, 4], dtype=int64)

#Values Series 2

In [21]:
#ANSWER
ser1.index

Index(['USA', 'Germany', 'USSR', 'Japan'], dtype='object')

In [22]:
#ANSWER
d2.index

Index(['USA', 'Germany', 'USSR', 'Japan'], dtype='object')

#Buat Random integer 1 hingga 5 sebanyak 15 bilangan, tampilkan hanya nilai uniquenya saja


In [24]:
#ANSWER
d1 = np.random.randint(1,5,15)
d1

array([4, 4, 2, 3, 4, 4, 2, 4, 4, 2, 2, 1, 1, 4, 1])

In [25]:
d2 = np.unique(d1)
d2

array([1, 2, 3, 4])

#Buat Random integer 1 hingga 5 sebanyak 15 bilangan, tampilkan berapa banyak nilai unique uniquenya saja


#Buat Random integer 1 hingga 5 sebanyak 15 bilangan, tampilkan frekuensi setiap bilangannya

0    1
1    2
2    3
3    4
dtype: int64

In [28]:
d1

array([4, 4, 2, 3, 4, 4, 2, 4, 4, 2, 2, 1, 1, 4, 1])

In [46]:
dict1 = {}
for i in d1 :
    # print(f"i : {i}")
    if i in dict1:
        dict1[i] +=1
    else:
        dict1[i] =1
# dict1
pd.Series(dict1)

4    7
2    4
3    1
1    3
dtype: int64

## Data Frame

In [30]:
from numpy.random import seed, randn
seed(101)

In [31]:
#dataframe adalah sekumpulan series yang ditempel menjadi 1 dan berbagi index. 

df =pd.DataFrame(randn(5,4), index =list('ABCDE'), columns = list('WXYZ'))

In [32]:
#ANSWER
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
E  0.190794  1.978757  2.605967  0.683509

In [33]:
#ANSWER
E = df.iloc[[4]]
df.append(E)


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
E  0.190794  1.978757  2.605967  0.683509

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [34]:
#ANSWER
df[["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [35]:
#ANSWER
df.iloc[:,0]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

## Creating New Column

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2
D  0.188695 -0.758872 -0.933237  0.955057     3
E  0.190794  1.978757  2.605967  0.683509     4

In [36]:
#ANSWER
df2 = df.assign(NEW = ['Text',1,2,3,4])
df2

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2
D  0.188695 -0.758872 -0.933237  0.955057     3
E  0.190794  1.978757  2.605967  0.683509     4

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2
D  0.188695 -0.758872 -0.933237  0.955057     3

In [37]:
#ANSWER
df2.drop(index = 'E')

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2
D  0.188695 -0.758872 -0.933237  0.955057     3

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1

In [38]:
#ANSWER
df2.drop(index = ["C","D","E"])

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1

In [48]:
#ANSWER
df2.loc["A":"B"]

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2

In [39]:
#ANSWER
df2.drop(index = ["D","E"])

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2

W   NEW
A  2.706850  Text
C -2.018168     2

In [40]:
#ANSWER
df2.drop(index = ["B","D","E"], columns=["X","Y","Z"])

W   NEW
A  2.706850  Text
C -2.018168     2

## Conditional Selection

In [49]:
df2

W         X         Y         Z   NEW
A  2.706850  0.628133  0.907969  0.503826  Text
B  0.651118 -0.319318 -0.848077  0.605965     1
C -2.018168  0.740122  0.528813 -0.589001     2
D  0.188695 -0.758872 -0.933237  0.955057     3
E  0.190794  1.978757  2.605967  0.683509     4

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
#Tampilkan dataframe yang W nya lebih besar dari 0


In [43]:
#ANSWER
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509