In [4]:
import numpy as np 
import pandas as pd
import string

# NO 1

In [33]:
start = int(input("Masukan nilai start : "))
end = int(input("Masukan nilai end : "))
arr1 = np.arange(start, end)

In [34]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [35]:
arr1.reshape(3,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [37]:
arr1.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [38]:
arr1.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [43]:
arr1.reshape(3,3,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# NO 2

In [12]:
n = int(input("Masukan banyaknya data : "))
mulai = int(input("Mulai : "))
batas = int(input("Selesai : "))
arr2 = np.random.randint(mulai,batas,n)
arr2

array([23, 47, 22,  9, 46, 37, 34, 17, 15, 30, 26, 32, 32, 45, 48, 47])

In [14]:
a1 = arr2.reshape(4,4)
a1

array([[23, 47, 22,  9],
       [46, 37, 34, 17],
       [15, 30, 26, 32],
       [32, 45, 48, 47]])

In [17]:
rev1 = a1[:,::-1]
rev1

array([[ 9, 22, 47, 23],
       [17, 34, 37, 46],
       [32, 26, 30, 15],
       [47, 48, 45, 32]])

In [10]:
a = arr2.reshape(2,2,4)
a

array([[[32,  8, 43,  6],
        [31, 43,  8, 32]],

       [[17, 14, 35, 22],
        [48,  2, 36, 35]]])

In [19]:
b = np.flip(a,0)
b

array([[[17, 14, 35, 22],
        [48,  2, 36, 35]],

       [[32,  8, 43,  6],
        [31, 43,  8, 32]]])

In [21]:
rev = a[:,::-1,:]
rev.reshape(2,2,4)

array([[[31, 43,  8, 32],
        [32,  8, 43,  6]],

       [[48,  2, 36, 35],
        [17, 14, 35, 22]]])

# TUKAR POSISI MASIH SALAH

# NO 3

In [56]:
t1 = np.full((10,10),4)
t2 = np.full((8,8),0)
t1[1:-1,1:-1]=t2
t1

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [44]:
t1 = np.full((10,10),4)
t1[1:-1,1:-1]=0
t1

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

# NO 4

In [7]:
abjad = np.array(list(string.ascii_lowercase)) #harus import string dulu
value = np.arange(1,27)
series = pd.Series(data = value, index = abjad)
series

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

In [64]:
t3 =[x for x in range(1,27)]
t3 = pd.Series(t3,index = (i for i in 'abcdefghijklmnopqrstuvwxyz'))
t3

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

# no 5

In [66]:
a = np.random.randint(1,5,100)
a = pd.Series(a)
a

0     1
1     2
2     2
3     1
4     4
     ..
95    3
96    2
97    2
98    2
99    1
Length: 100, dtype: int32

In [80]:
b = a.value_counts()
b

2    34
4    25
1    21
3    20
dtype: int64

In [95]:
print(f"Top 2 freq adalah {b.index[0]} dengan frekuensi sebanyak {b[b.index[0]]} dan {b.index[1]} dengan frekuensi sebanyak {b[b.index[1]]} ")
# print("Top 2 freq adalah",b.index[0],"dengan frekuensi sebanyak",b[b.index[0]],"dan",b.index[1],"dengan frekuensi sebanyak",b[b.index[1]])
# b.index[0]
# b[b.index[0]]

Top 2 freq adalah 2 dengan frekuensi sebanyak 34 dan 4 dengan frekuensi sebanyak 25 


# no 6

In [22]:
import seaborn as sns

In [23]:
mpg = sns.load_dataset('mpg')

In [24]:
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [25]:
mpg.describe(exclude="number")

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [26]:
len(mpg)

398

In [102]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [28]:
mpg.isna().sum()/len(mpg)*100

mpg             0.000000
cylinders       0.000000
displacement    0.000000
horsepower      1.507538
weight          0.000000
acceleration    0.000000
model_year      0.000000
origin          0.000000
name            0.000000
dtype: float64

# no 7

In [29]:
mpg[mpg['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [110]:
mpg[mpg["horsepower"].isna()].index

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

# no 8

In [135]:
group = mpg.groupby("origin")
group.mean()['horsepower']

origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

# no 9

In [117]:
def add_horse_origin(x):
    if x['horsepower'] <= 105 :
        return 'lower {}'.format(x['origin'])
    else :
        return 'upper {}'.format(x['origin'])

In [51]:
mpg['horse_origin'] = mpg[['horsepower', 'originorigin']].apply(add_horse_origin, axis = 1)
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

# no 10

In [137]:
group["weight"].describe()


count         mean         std     min      25%     50%      75%  \
origin                                                                     
europe   70.0  2423.300000  490.043191  1825.0  2067.25  2240.0  2769.75   
japan    79.0  2221.227848  320.497248  1613.0  1985.00  2155.0  2412.50   
usa     249.0  3361.931727  794.792506  1800.0  2720.00  3365.0  4054.00   

           max  
origin          
europe  3820.0  
japan   2930.0  
usa     5140.0

In [52]:
group["weight"].agg(['mean','median','std','sum','count','min','max'])

mean  median         std     sum  count   min   max
origin                                                            
europe  2423.300000    2240  490.043191  169631     70  1825  3820
japan   2221.227848    2155  320.497248  175477     79  1613  2930
usa     3361.931727    3365  794.792506  837121    249  1800  5140

In [140]:
group.median().loc['usa']

mpg               18.5
cylinders          6.0
displacement     250.0
horsepower       105.0
weight          3365.0
acceleration      15.0
model_year        76.0
Name: usa, dtype: float64

In [142]:
group.agg(['median','mean'])#bisa tambahin .loc[countrynya apa]

mpg            cylinders           displacement              \
       median       mean    median      mean       median        mean   
origin                                                                  
europe   26.5  27.891429         4  4.157143        104.5  109.142857   
japan    31.6  30.450633         4  4.101266         97.0  102.708861   
usa      18.5  20.083534         6  6.248996        250.0  245.901606   

       horsepower             weight              acceleration             \
           median        mean median         mean       median       mean   
origin                                                                      
europe       76.5   80.558824   2240  2423.300000         15.7  16.787143   
japan        75.0   79.835443   2155  2221.227848         16.4  16.172152   
usa         105.0  119.048980   3365  3361.931727         15.0  15.033735   

       model_year             
           median       mean  
origin                        
europe         76  75.814286  
japan          78  77.443038  
usa            76  75.610442