In [2]:
import pandas as pd 
import numpy as np 

# CREATING NUMPY ARRAYS

In [396]:
#1D
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [397]:
#2D array
my_matrix = [[1,2,3],[4,5,6]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [398]:
NP1 = np.arange(0,10)
NP1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [399]:
NP2 = np.arange(0,20,2) #start, end, step
NP2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [400]:
NP3 = np.zeros(10)
NP3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [401]:
NP4 = np.full(10,1)
NP4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [402]:
NP5 = np.ones(10)
NP5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [403]:
NP6 = np.eye(4)
NP6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [404]:
NP7 = np.identity(4)
NP7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [405]:
NP8 = np.linspace(0,10,3) #start, stop, dibagi jd brp bagian scr rata. 
NP8

array([ 0.,  5., 10.])

In [406]:
NP9 = np.random.rand(10) #random antara 0-1
NP9

array([0.16193789, 0.94897702, 0.05944908, 0.88649949, 0.57434422,
       0.3788469 , 0.64090526, 0.127807  , 0.40670287, 0.35641009])

In [407]:
NP10 = np.random.randn(10) #random normal stdev 1 mean = 0
NP10

array([ 0.07112476, -0.06960258, -0.22338168, -1.22826971, -2.45743268,
       -0.52512255,  0.36959129, -0.47921581,  0.3203879 , -1.23621312])

In [408]:
NP11 = np.random.randint(1,100,10) # hasilnya integer (start, end, banyaknya)
NP11

array([85,  1, 17, 31,  4, 79, 60, 54, 70, 50])

In [409]:
NP12 = np.random.randint(1,100,(5,5))
NP12

array([[75, 47, 28, 34, 73],
       [69, 40, 33, 98,  8],
       [34, 63, 15, 78, 44],
       [62, 86, 37, 13, 54],
       [27, 83, 13, 26,  2]])

In [410]:
NP14 = np.full((3,3),88)
NP14

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [411]:
NP15 = np.full_like(NP14,55)
NP15

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [412]:
NP16 = np.arange(1,4).reshape(1,3)
NP16

array([[1, 2, 3]])

In [413]:
NP17 = np.repeat(NP16,3, axis =0)
NP17

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [414]:
NP18 = np.repeat(NP16,3,axis = 1)
NP18

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

Shape & Re-Shape

In [415]:
NP11.shape  #untuk tau shape & dimensinya

(10,)

In [416]:
NP12.shape

(5, 5)

In [417]:
NP11.reshape(2,5) #untuk ngubah shape

array([[85,  1, 17, 31,  4],
       [79, 60, 54, 70, 50]])

In [418]:
NP11.reshape(1,10) #perbedaan dgn NP11 biasa, kurung sikunya jadi 2. nunjukin kalau arraynya 2d

array([[85,  1, 17, 31,  4, 79, 60, 54, 70, 50]])

In [419]:
NP12.reshape(-1)

array([75, 47, 28, 34, 73, 69, 40, 33, 98,  8, 34, 63, 15, 78, 44, 62, 86,
       37, 13, 54, 27, 83, 13, 26,  2])

In [420]:
NP12.reshape(-1).shape #-1 ngebalikin jadi array 2d jadi array 1d

(25,)

Array Attributes and Methods

In [421]:
NP11

array([85,  1, 17, 31,  4, 79, 60, 54, 70, 50])

In [422]:
NP11.max() #nampilin nilai max

85

In [423]:
NP11.argmax() #nampilin index dr nilai max

0

In [424]:
NP11.min() #nampilin nilai min

1

In [425]:
NP11.argmin() # nampilin index dr nilai min

1

In [426]:
NP11.sum() #ngejumlahin semua nilai

451

In [427]:
np.sin(NP11)

array([-0.17607562,  0.84147098, -0.96139749, -0.40403765, -0.7568025 ,
       -0.44411267, -0.30481062, -0.55878905,  0.77389068, -0.26237485])

cek tipe data & size

In [428]:
NP11.dtype #nanti bisa float, object, dll
#16,32,64 di blkngnya nunjukin besar ukuran filenya

dtype('int32')

In [429]:
NP11.itemsize

4

In [430]:
NP11.size

10

In [431]:
NP11.nbytes #itemsize * size

40

Numpy Indexing & Slicing

In [432]:
NP13 = np.arange(0,11)
NP13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [433]:
NP13[5] #nampilin value dari index ke 5. index mulai dr 0

5

In [434]:
NP13[3:6]

array([3, 4, 5])

In [435]:
NP13[2:10:2] #start, stop, step

array([2, 4, 6, 8])

In [436]:
NP13[6:10] = 100 #merubah value index ke 6-10
NP13

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100,  10])

In [437]:
NP12

array([[75, 47, 28, 34, 73],
       [69, 40, 33, 98,  8],
       [34, 63, 15, 78, 44],
       [62, 86, 37, 13, 54],
       [27, 83, 13, 26,  2]])

In [438]:
NP12[1] #nampilin row1

array([69, 40, 33, 98,  8])

In [439]:
NP12[3,3] #nampilin row index 3, column index 3

13

In [440]:
#nampilin 4 kotak kiri atas dr NP12
NP12[:2,:2]

array([[75, 47],
       [69, 40]])

In [441]:
#nampilin diagonal
NP12[[0,1,2,3,4],[0,1,2,3,4]]

array([75, 40, 15, 13,  2])

In [442]:
#nampilin 2 kanan atas, 4 kanan bawah
NP12[[0,3,4],3:]

array([[34, 73],
       [13, 54],
       [26,  2]])

In [443]:
NP12[3][3] #format penulisan bisa dipisah

13

In [444]:
NP12[:,3] #ambil dari semua baris, index ke 3

array([34, 98, 78, 13, 26])

COPY

In [445]:
NP14 = NP13.copy() #lebih aman di copy daripada di 'sama dengan'
NP14

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100,  10])

Conditional Selection

In [446]:
NP12

array([[75, 47, 28, 34, 73],
       [69, 40, 33, 98,  8],
       [34, 63, 15, 78, 44],
       [62, 86, 37, 13, 54],
       [27, 83, 13, 26,  2]])

In [447]:
NP12>20

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True, False]])

In [448]:
NP20 = NP12[NP12>20] #bisa dipake buat array baru juga
NP20

array([75, 47, 28, 34, 73, 69, 40, 33, 98, 34, 63, 78, 44, 62, 86, 37, 54,
       27, 83, 26])

SPECIAL CONTOH

In [449]:
NP21 = np.full((10,10),4)
NP22 = np.full((8,8),0)
NP21[1:-1,1:-1]=NP22
# FORMAT PENULISAN LAINNYA
# NP21[1:9,1:9]=NP22 
NP21

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

BROADCASTING
syarat : 
- the same
- or one of them is one (perhatiin jumlah row & columnnya)

Arithmetic

bisa * / + -

akan di hitung per value

np.sqrt(array)

np.exp(array)

np.sin(array)

np.log(array)

Other Function

In [112]:
NP11

array([50,  4, 13, 80, 20, 14, 64, 29, 49, 98])

In [114]:
np.insert(NP11,5,1000) #pada NP11 nambahin di index ke 5, value 1000

array([  50,    4,   13,   80,   20, 1000,   14,   64,   29,   49,   98])

In [116]:
np.delete(NP11,0)

array([ 4, 13, 80, 20, 14, 64, 29, 49, 98])

In [117]:
np.append(NP11,1000)

array([  50,    4,   13,   80,   20,   14,   64,   29,   49,   98, 1000])

In [120]:
np.concatenate((NP12,NP12),axis = 1) #nambah ke column krn axis = 1

array([[71, 34, 70, 47, 94, 71, 34, 70, 47, 94],
       [57, 10, 30, 27, 33, 57, 10, 30, 27, 33],
       [70, 53, 26, 44, 68, 70, 53, 26, 44, 68],
       [ 5, 82, 15, 15, 93,  5, 82, 15, 15, 93],
       [70, 81, 19, 25, 75, 70, 81, 19, 25, 75]])

In [121]:
np.concatenate((NP12,NP12)) #by default or axis = 0, nambahinnya baris ke bawah

array([[71, 34, 70, 47, 94],
       [57, 10, 30, 27, 33],
       [70, 53, 26, 44, 68],
       [ 5, 82, 15, 15, 93],
       [70, 81, 19, 25, 75],
       [71, 34, 70, 47, 94],
       [57, 10, 30, 27, 33],
       [70, 53, 26, 44, 68],
       [ 5, 82, 15, 15, 93],
       [70, 81, 19, 25, 75]])

In [122]:
np.concatenate((NP12,NP12),axis = None)
#nambahin tapi ngubah jd 1d

array([71, 34, 70, 47, 94, 57, 10, 30, 27, 33, 70, 53, 26, 44, 68,  5, 82,
       15, 15, 93, 70, 81, 19, 25, 75, 71, 34, 70, 47, 94, 57, 10, 30, 27,
       33, 70, 53, 26, 44, 68,  5, 82, 15, 15, 93, 70, 81, 19, 25, 75])

In [124]:
np.concatenate((NP12,NP12),axis = None).shape

(50,)

In [126]:
NP12

array([[71, 34, 70, 47, 94],
       [57, 10, 30, 27, 33],
       [70, 53, 26, 44, 68],
       [ 5, 82, 15, 15, 93],
       [70, 81, 19, 25, 75]])

In [127]:
np.where(NP12>20,True,False) #syarat, value if true, value if false

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True,  True, False,  True,  True]])

In [129]:
np.where(NP12%2==0,"Genap",NP12) #nampilin kalo genap jadi tulisan "GENAP", kalo ganjil tetap bilangan itu

array([['71', 'Genap', 'Genap', '47', 'Genap'],
       ['57', 'Genap', 'Genap', '27', '33'],
       ['Genap', '53', 'Genap', 'Genap', 'Genap'],
       ['5', 'Genap', '15', '15', '93'],
       ['Genap', '81', '19', '25', '75']], dtype='<U11')

# PANDAS

# Series

In [139]:
labels_ser1 = ['a','b','c']
list_ser1 = [1,2,3]

In [140]:
pd.Series(data = list_ser1, index = labels_ser1)

a    1
b    2
c    3
dtype: int64

In [141]:
pd.Series(list_ser1,labels_ser1) #bisa langsung

a    1
b    2
c    3
dtype: int64

In [130]:
pd.Series(np.arange(1,10))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

In [137]:
ser1 = {'a':10,'b':20,'c':30}
pd.Series(ser1)

a    10
b    20
c    30
dtype: int64

# Data Frame

In [154]:
A1 = [i for i in range(1,6)]
A2 = [i for i in 'abcde']
A3 = np.random.randint(1,5,5)

In [156]:
pd.DataFrame(data = [A1,A2,A3])

0  1  2  3  4
0  1  2  3  4  5
1  a  b  c  d  e
2  3  1  4  3  1

In [157]:
pd.DataFrame(data = list(zip(A1,A2,A3)))

0  1  2
0  1  a  3
1  2  b  1
2  3  c  4
3  4  d  3
4  5  e  1

In [164]:
df1 = pd.DataFrame(np.random.randint(1,10,(5,4)),index = 'A B C D E'.split(), columns='W X Y Z'.split())
df1

W  X  Y  Z
A  7  8  7  2
B  1  2  9  9
C  4  9  8  4
D  7  6  2  4
E  5  9  2  5

Selection & Indexing DF

In [166]:
df1["W"]

A    7
B    1
C    4
D    7
E    5
Name: W, dtype: int32

In [169]:
df1["W"][0:2]

A    7
B    1
Name: W, dtype: int32

In [171]:
type(df1["W"])

pandas.core.series.Series

In [172]:
df1["min"] = [1,2,3,4,5]
df1

W  X  Y  Z  min
A  7  8  7  2    1
B  1  2  9  9    2
C  4  9  8  4    3
D  7  6  2  4    4
E  5  9  2  5    5

In [174]:
df1[["W","min"]]

W  min
A  7    1
B  1    2
C  4    3
D  7    4
E  5    5

INDEXING LOX & ILOC

In [180]:
df1.loc["A"]

W      7
X      8
Y      7
Z      2
min    1
Name: A, dtype: int64

In [177]:
df1.iloc[0] #pake index

W      7
X      8
Y      7
Z      2
min    1
Name: A, dtype: int64

In [181]:
df1.loc["A"][2]

7

In [183]:
df1.iloc[[1,3]] #semua data dr row 1-2 aja

W  X  Y  Z  min
B  1  2  9  9    2
D  7  6  2  4    4

In [182]:
df1.iloc[2][2] #data dr row 2 col 2

8

In [184]:
df1>5

W      X      Y      Z    min
A   True   True   True  False  False
B  False  False   True   True  False
C  False   True   True  False  False
D   True   True  False  False  False
E  False   True  False  False  False

In [192]:
df1[df1>5]

W    X    Y    Z  min
A  7.0  8.0  7.0  NaN  NaN
B  NaN  NaN  9.0  9.0  NaN
C  NaN  9.0  8.0  NaN  NaN
D  7.0  6.0  NaN  NaN  NaN
E  NaN  9.0  NaN  NaN  NaN

In [194]:
df1[df1["W"]>5] #nampilin semua kolom dimana syaratnya kolom W

W  X  Y  Z  min
A  7  8  7  2    1
D  7  6  2  4    4

In [195]:
df1[df1["W"]>5]["Y"] #nampilin kolom Y kalo kolom W nya memenuhi syarat

A    7
D    2
Name: Y, dtype: int32

In [197]:
df1[(df1["W"]>3) & (df1["Y"] >1)] 
#bisa 2 syarat
#harus pake simbol & = and | = or
#jangan lupa pake kurung untuk setiap kondisinya

W  X  Y  Z  min
A  7  8  7  2    1
C  4  9  8  4    3
D  7  6  2  4    4
E  5  9  2  5    5

# DATA FRAME MANIPULATION 
Add row, remove row, drop

In [201]:
#add row
df1.loc["new"] = [1,2,3,4,5] 
df1

W  X  Y  Z  min
A    7  8  7  2    1
B    1  2  9  9    2
C    4  9  8  4    3
D    7  6  2  4    4
E    5  9  2  5    5
new  1  2  3  4    5

In [202]:
#add column
df1["NEW"]=["A","B","C","D","E","F"]
df1

W  X  Y  Z  min NEW
A    7  8  7  2    1   A
B    1  2  9  9    2   B
C    4  9  8  4    3   C
D    7  6  2  4    4   D
E    5  9  2  5    5   E
new  1  2  3  4    5   F

In [203]:
#INSERT
df1.insert(2,'NEW1',[5,6,7,8,9,10])
df1

W  X  NEW1  Y  Z  min NEW
A    7  8     5  7  2    1   A
B    1  2     6  9  9    2   B
C    4  9     7  8  4    3   C
D    7  6     8  2  4    4   D
E    5  9     9  2  5    5   E
new  1  2    10  3  4    5   F

In [208]:
#DELETE
#hapus kolom 1. axis = 1 itu kolom

#kalo mau permanent pake inplace = True

df1.drop('NEW',axis=1)

W  X  NEW1  Y  Z  min
A    7  8     5  7  2    1
B    1  2     6  9  9    2
C    4  9     7  8  4    3
D    7  6     8  2  4    4
E    5  9     9  2  5    5
new  1  2    10  3  4    5

In [209]:
#hapus baris 1
df1.drop("new",axis=0)

W  X  NEW1  Y  Z  min NEW
A  7  8     5  7  2    1   A
B  1  2     6  9  9    2   B
C  4  9     7  8  4    3   C
D  7  6     8  2  4    4   D
E  5  9     9  2  5    5   E

In [210]:
#reset index
#untuk ngubah index jd angka
df1.reset_index()

index  W  X  NEW1  Y  Z  min NEW
0     A  7  8     5  7  2    1   A
1     B  1  2     6  9  9    2   B
2     C  4  9     7  8  4    3   C
3     D  7  6     8  2  4    4   D
4     E  5  9     9  2  5    5   E
5   new  1  2    10  3  4    5   F

In [211]:
df1.set_index("NEW")
#kalau mau permanent pake inplace = True

W  X  NEW1  Y  Z  min
NEW                       
A    7  8     5  7  2    1
B    1  2     6  9  9    2
C    4  9     7  8  4    3
D    7  6     8  2  4    4
E    5  9     9  2  5    5
F    1  2    10  3  4    5

# Multi Indexing
Hati2 penulisan kalo pake xs pake ()
kalo .loc pake kurung siku []

In [221]:
d = {'num_legs': [4, 4, 2, 2],
     'num_wings': [0, 0, 2, 2],
     'class': ['mammal', 'mammal', 'mammal', 'bird'],
     'animal': ['cat', 'dog', 'bat', 'penguin'],
     'locomotion': ['walks', 'walks', 'flies', 'walks']}
df2 = pd.DataFrame(data=d)
df2 = df2.set_index(['class', 'animal', 'locomotion'])
df2

num_legs  num_wings
class  animal  locomotion                     
mammal cat     walks              4          0
       dog     walks              4          0
       bat     flies              2          2
bird   penguin walks              2          2

In [223]:
df2.xs('mammal')

num_legs  num_wings
animal locomotion                     
cat    walks              4          0
dog    walks              4          0
bat    flies              2          2

In [252]:
df2.loc['mammal']

num_legs  num_wings
animal locomotion                     
cat    walks              4          0
dog    walks              4          0
bat    flies              2          2

In [224]:
df2.xs(('mammal', 'dog'))

C:\Users\lidya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\IPython\core\interactiveshell.py:2940: PerformanceWarning: indexing past lexsort depth may impact performance.
  return runner(coro)


num_legs  num_wings
locomotion                     
walks              4          0

In [225]:
df2.xs('cat', level=1)

num_legs  num_wings
class  locomotion                     
mammal walks              4          0

In [226]:
df2.xs(('bird', 'walks'),
      level=[0, 'locomotion'])

num_legs  num_wings
animal                      
penguin         2          2

In [228]:
df2.xs('num_wings', axis=1)

class   animal   locomotion
mammal  cat      walks         0
        dog      walks         0
        bat      flies         2
bird    penguin  walks         2
Name: num_wings, dtype: int64

In [286]:
Luar = ['Bandung','Bandung','Bandung','Bandung','Bandung','Bandung','Kendari','Kendari','Kendari','Kendari','Kendari','Kendari','Solo','Solo','Solo','Solo','Solo','Solo',]
Dalam = [1,2,3,4,5,6,1,2,3,4,5,6,1,2,3,4,5,6,]
Index = list(zip(Luar,Dalam))
Index

[('Bandung', 1),
 ('Bandung', 2),
 ('Bandung', 3),
 ('Bandung', 4),
 ('Bandung', 5),
 ('Bandung', 6),
 ('Kendari', 1),
 ('Kendari', 2),
 ('Kendari', 3),
 ('Kendari', 4),
 ('Kendari', 5),
 ('Kendari', 6),
 ('Solo', 1),
 ('Solo', 2),
 ('Solo', 3),
 ('Solo', 4),
 ('Solo', 5),
 ('Solo', 6)]

In [237]:
hier_index = pd.MultiIndex.from_tuples(Index)
hier_index

MultiIndex([('Bandung', 1),
            ('Bandung', 2),
            ('Bandung', 3),
            ('Bandung', 4),
            ('Bandung', 5),
            ('Bandung', 6),
            ('Kendari', 1),
            ('Kendari', 2),
            ('Kendari', 3),
            ('Kendari', 4),
            ('Kendari', 5),
            ('Kendari', 6),
            (   'Solo', 1),
            (   'Solo', 2),
            (   'Solo', 3),
            (   'Solo', 4),
            (   'Solo', 5),
            (   'Solo', 6)],
           )

In [378]:
df3 = pd.DataFrame(np.random.randint(1,100,(18,5)),index = hier_index,columns=['Cabang A','Cabang B','Cabang C','Cabang D','Cabang E'])
df3

Cabang A  Cabang B  Cabang C  Cabang D  Cabang E
Kota    Lokasi                                                  
Bandung 1             33        47        64        94        19
        2             37        30        40        29        55
        3             30        56        91        28        61
        4             13        18        72        92         8
        5             84        57        52        33        77
        6             63        52        97        31        23
Kendari 1              6        92        96        23        77
        2             23        19        94        30        19
        3             53        32        50        99        84
        4             94        46        52        87        16
        5             72        49        29        84        28
        6             44        20        80        71        89
Solo    1             87        12        66        94        16
        2             52        99        87        46        64
        3             43        23        83        41        45
        4             17        18        89         1        98
        5             83        72        15        37        27
        6             33         2        49        89        23

In [350]:
df3.loc["Kendari"]

Cabang A  Cabang B  Cabang C  Cabang D  Cabang E
Lokasi                                                  
1             96        97        61        44        32
2             45        25        63        80        22
3             20        78        34         5        40
4             68        35        35        43        79
5             83        39        49        82         6
6             92         9        41        70         6

In [351]:
df3.xs('Kendari')

Cabang A  Cabang B  Cabang C  Cabang D  Cabang E
Lokasi                                                  
1             96        97        61        44        32
2             45        25        63        80        22
3             20        78        34         5        40
4             68        35        35        43        79
5             83        39        49        82         6
6             92         9        41        70         6

In [391]:
df3.loc['Solo']

Cabang A  Cabang B  Cabang C  Cabang D  Cabang E
Lokasi                                                  
1             87        12        66        94        16
2             52        99        87        46        64
3             43        23        83        41        45
4             17        18        89         1        98
5             83        72        15        37        27
6             33         2        49        89        23

In [451]:
df3.loc['Solo'].loc[6]

Cabang A    33
Cabang B     2
Cabang C    49
Cabang D    89
Cabang E    23
Name: 6, dtype: int32

In [393]:
df3.loc['Solo'].loc[[4,6]]

Cabang A  Cabang B  Cabang C  Cabang D  Cabang E
Lokasi                                                  
4             17        18        89         1        98
6             33         2        49        89        23

In [394]:
df3.xs(['Bandung',3])

Cabang A    30
Cabang B    56
Cabang C    91
Cabang D    28
Cabang E    61
Name: (Bandung, 3), dtype: int32

In [355]:
df3.index.names = ["Kota","Lokasi"]

In [356]:
df3

Cabang A  Cabang B  Cabang C  Cabang D  Cabang E
Kota    Lokasi                                                  
Bandung 1             82        11        73        49        20
        2             13        26        78        17         5
        3             89        28        51        69         4
        4             59        13         3        77        97
        5             97        62        16        75        13
        6             19        31        60         6        17
Kendari 1             96        97        61        44        32
        2             45        25        63        80        22
        3             20        78        34         5        40
        4             68        35        35        43        79
        5             83        39        49        82         6
        6             92         9        41        70         6
Solo    1              8        79        38        79        34
        2             28        52        78        31        44
        3             47        10        68         4        68
        4             55        98        64        81        29
        5             38        65        38        94        19
        6             79        71        93        53        11

# SORTING
df.sort_values("nama kolomnya")
secara default sort akan secara ascending

bisa juga:
df.sort_index(ascending = False) 

supaya descending : 
df.sort_values("nama kolom", ascending = False)

kalau mau permanent, inplace = True

In [357]:
dt = pd.read_csv("netflix_titles.csv")

In [358]:
dt1 = dt.head(10)
dt1

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   
5      s6  TV Show     46        Serdar Akar   
6      s7    Movie    122    Yasir Al Yasiri   
7      s8    Movie    187     Kevin Reynolds   
8      s9    Movie    706      Shravan Kumar   
9     s10    Movie   1920       Vikram Bhatt   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   
5  Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...         Turkey   
6  Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...          Egypt   
7  Samuel L. Jackson, John Heard, Kelly Rowan, Cl...  United States   
8  Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...          India   
9  Rajneesh Duggal, Adah Sharma, Indraneil Sengup...          India   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   
5       July 1, 2017          2016  TV-MA   1 Season   
6       June 1, 2020          2019  TV-MA     95 min   
7   November 1, 2019          1997      R    119 min   
8      April 1, 2019          2019  TV-14    118 min   
9  December 15, 2017          2008  TV-MA    143 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   
5    International TV Shows, TV Dramas, TV Mysteries   
6                Horror Movies, International Movies   
7                                             Dramas   
8                Horror Movies, International Movies   
9     Horror Movies, International Movies, Thrillers   

                                         description  
0  In a future where the elite inhabit an island ...  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...  
5  A genetics professor experiments with a treatm...  
6  After an awful accident, a couple admitted to ...  
7  After one of his high school students attacks ...  
8  When a doctor goes missing, his psychiatrist w...  
9  An architect and his wife move into a castle t...

In [359]:
dt1.sort_values("director")

show_id     type  title           director  \
2      s3    Movie  23:59       Gilbert Chan   
1      s2    Movie   7:19  Jorge Michel Grau   
7      s8    Movie    187     Kevin Reynolds   
4      s5    Movie     21     Robert Luketic   
5      s6  TV Show     46        Serdar Akar   
3      s4    Movie      9        Shane Acker   
8      s9    Movie    706      Shravan Kumar   
9     s10    Movie   1920       Vikram Bhatt   
6      s7    Movie    122    Yasir Al Yasiri   
0      s1  TV Show     3%                NaN   

                                                cast        country  \
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
7  Samuel L. Jackson, John Heard, Kelly Rowan, Cl...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   
5  Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...         Turkey   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
8  Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...          India   
9  Rajneesh Duggal, Adah Sharma, Indraneil Sengup...          India   
6  Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...          Egypt   
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   

          date_added  release_year rating   duration  \
2  December 20, 2018          2011      R     78 min   
1  December 23, 2016          2016  TV-MA     93 min   
7   November 1, 2019          1997      R    119 min   
4    January 1, 2020          2008  PG-13    123 min   
5       July 1, 2017          2016  TV-MA   1 Season   
3  November 16, 2017          2009  PG-13     80 min   
8      April 1, 2019          2019  TV-14    118 min   
9  December 15, 2017          2008  TV-MA    143 min   
6       June 1, 2020          2019  TV-MA     95 min   
0    August 14, 2020          2020  TV-MA  4 Seasons   

                                           listed_in  \
2                Horror Movies, International Movies   
1                       Dramas, International Movies   
7                                             Dramas   
4                                             Dramas   
5    International TV Shows, TV Dramas, TV Mysteries   
3  Action & Adventure, Independent Movies, Sci-Fi...   
8                Horror Movies, International Movies   
9     Horror Movies, International Movies, Thrillers   
6                Horror Movies, International Movies   
0  International TV Shows, TV Dramas, TV Sci-Fi &...   

                                         description  
2  When an army recruit is found dead, his fellow...  
1  After a devastating earthquake hits Mexico Cit...  
7  After one of his high school students attacks ...  
4  A brilliant group of students become card-coun...  
5  A genetics professor experiments with a treatm...  
3  In a postapocalyptic world, rag-doll robots hi...  
8  When a doctor goes missing, his psychiatrist w...  
9  An architect and his wife move into a castle t...  
6  After an awful accident, a couple admitted to ...  
0  In a future where the elite inhabit an island ...

# PANDAS FUNCTIONALITY

In [360]:
#head contoh di atas
dt.tail(10)

show_id     type                                    title  \
7777   s7778  TV Show                              Zombie Dumb   
7778   s7779    Movie                               Zombieland   
7779   s7780  TV Show                                Zona Rosa   
7780   s7781    Movie                                      Zoo   
7781   s7782    Movie                                     Zoom   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

             director                                               cast  \
7777              NaN                                                NaN   
7778  Ruben Fleischer  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...   
7779              NaN  Manu NNa, Ana Julia Yeyé, Ray Contreras, Pablo...   
7780     Shlok Sharma  Shashank Arora, Shweta Tripathi, Rahul Kumar, ...   
7781     Peter Hewitt  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...   
7782      Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783      Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784              NaN                                            Nasty C   
7785              NaN                         Adriano Zumbo, Rachel Khoo   
7786         Sam Dunn                                                NaN   

                                                country          date_added  \
7777                                                NaN        July 1, 2019   
7778                                      United States    November 1, 2019   
7779                                             Mexico   November 26, 2019   
7780                                              India        July 1, 2018   
7781                                      United States    January 11, 2020   
7782  Sweden, Czech Republic, United Kingdom, Denmar...    October 19, 2020   
7783                                              India       March 2, 2019   
7784                                                NaN  September 25, 2020   
7785                                          Australia    October 31, 2020   
7786              United Kingdom, Canada, United States       March 1, 2020   

      release_year rating   duration  \
7777          2018  TV-Y7  2 Seasons   
7778          2009      R     88 min   
7779          2019  TV-MA   1 Season   
7780          2018  TV-MA     94 min   
7781          2006     PG     88 min   
7782          2005  TV-MA     99 min   
7783          2015  TV-14    111 min   
7784          2019  TV-MA     44 min   
7785          2019  TV-PG   1 Season   
7786          2019  TV-MA     90 min   

                                              listed_in  \
7777             Kids' TV, Korean TV Shows, TV Comedies   
7778                            Comedies, Horror Movies   
7779  International TV Shows, Spanish-Language TV Sh...   
7780   Dramas, Independent Movies, International Movies   
7781                 Children & Family Movies, Comedies   
7782                       Dramas, International Movies   
7783     Dramas, International Movies, Music & Musicals   
7784  Documentaries, International Movies, Music & M...   
7785                 International TV Shows, Reality TV   
7786                    Documentaries, Music & Musicals   

                                            description  
7777  While living alone in a spooky town, a young g...  
7778  Looking to survive in a world taken over by zo...  
7779  An assortment of talent takes the stage for a ...  
7780  A drug dealer starts having doubts about his t...  
7781  Dragged from civilian life, a former superhero...  
7782  When Lebanon's Civil War deprives Zozo of his ...  
7783  A scrappy but poor boy worms his way into a ty...  
7784  In this do

In [361]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB


In [362]:
dt.shape

(7787, 12)

In [363]:
dt.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [364]:
dt.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

Statistika Deskriptif

In [365]:
dt.describe() 
# secara default akan hitung yg number
# setara dengan include = "number"

release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [366]:
dt.describe(exclude="number") 
#jadi akan ngitung semua yg bukan number
#bisa juga include = "object", tapi cuma ngitung yg object aja

show_id   type     title                director                cast  \
count     7787   7787      7787                    5398                7069   
unique    7787      2      7787                    4049                6831   
top      s6209  Movie  Cocomong  Raúl Campos, Jan Suter  David Attenborough   
freq         1   5377         1                      18                  18   

              country       date_added rating  duration      listed_in  \
count            7280             7777   7780      7787           7787   
unique            681             1565     14       216            492   
top     United States  January 1, 2020  TV-MA  1 Season  Documentaries   
freq             2555              118   2863      1608            334   

                                              description  
count                                                7787  
unique                                               7769  
top     Multiple women report their husbands as missin...  
freq                                                    3

In [367]:
print("average:",dt['release_year'].mean())
print("median:",dt['release_year'].median())
print("standar deviation:",dt['release_year'].std())
print("minimum value:",dt['release_year'].min())
print("maximum value:",dt['release_year'].max())

average: 2013.932579940927
median: 2017.0
standar deviation: 8.757394618381273
minimum value: 1925
maximum value: 2021


In [368]:
dt['rating'].unique()

array(['TV-MA', 'R', 'PG-13', 'TV-14', 'TV-PG', 'NR', 'TV-G', 'TV-Y', nan,
       'TV-Y7', 'PG', 'G', 'NC-17', 'TV-Y7-FV', 'UR'], dtype=object)

In [369]:
dt['rating'].nunique()

14

In [370]:
dt['rating'].value_counts()

TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
TV-Y7-FV       6
UR             5
NC-17          3
Name: rating, dtype: int64

Missing Value

In [371]:
dt.isna()

show_id   type  title  director   cast  country  date_added  \
0       False  False  False      True  False    False       False   
1       False  False  False     False  False    False       False   
2       False  False  False     False  False    False       False   
3       False  False  False     False  False    False       False   
4       False  False  False     False  False    False       False   
...       ...    ...    ...       ...    ...      ...         ...   
7782    False  False  False     False  False    False       False   
7783    False  False  False     False  False    False       False   
7784    False  False  False      True  False     True       False   
7785    False  False  False      True  False    False       False   
7786    False  False  False     False   True    False       False   

      release_year  rating  duration  listed_in  description  
0            False   False     False      False        False  
1            False   False     False      False        False  
2            False   False     False      False        False  
3            False   False     False      False        False  
4            False   False     False      False        False  
...            ...     ...       ...        ...          ...  
7782         False   False     False      False        False  
7783         False   False     False      False        False  
7784         False   False     False      False        False  
7785         False   False     False      False        False  
7786         False   False     False      False        False  

[7787 rows x 12 columns]

In [372]:
dt.isna().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   
5      s6  TV Show     46        Serdar Akar   
6      s7    Movie    122    Yasir Al Yasiri   
7      s8    Movie    187     Kevin Reynolds   
8      s9    Movie    706      Shravan Kumar   
9     s10    Movie   1920       Vikram Bhatt   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   
5  Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...         Turkey   
6  Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...          Egypt   
7  Samuel L. Jackson, John Heard, Kelly Rowan, Cl...  United States   
8  Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...          India   
9  Rajneesh Duggal, Adah Sharma, Indraneil Sengup...          India   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   
5       July 1, 2017          2016  TV-MA   1 Season   
6       June 1, 2020          2019  TV-MA     95 min   
7   November 1, 2019          1997      R    119 min   
8      April 1, 2019          2019  TV-14    118 min   
9  December 15, 2017          2008  TV-MA    143 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   
5    International TV Shows, TV Dramas, TV Mysteries   
6                Horror Movies, International Movies   
7                                             Dramas   
8                Horror Movies, International Movies   
9     Horror Movies, International Movies, Thrillers   

                                         description  
0  In a future where the elite inhabit an island ...  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...  
5  A genetics professor experiments with a treatm...  
6  After an awful accident, a couple admitted to ...  
7  After one of his high school students attacks ...  
8  When a doctor goes missing, his psychiatrist w...  
9  An architect and his wife move into a castle t...

In [453]:
df1 = pd.DataFrame(np.random.randint(1,10,(5,4)),index = 'A B C D E'.split(), columns='W X Y Z'.split())
df1

W  X  Y  Z
A  8  8  1  9
B  7  2  3  1
C  5  5  7  2
D  1  5  4  1
E  6  2  2  7

In [485]:
df2 = df1[df1>1]
df2

W  X    Y    Z
A  8.0  8  NaN  9.0
B  7.0  2  3.0  NaN
C  5.0  5  7.0  2.0
D  NaN  5  4.0  NaN
E  6.0  2  2.0  7.0

# DROP & FILL

df.drop(columns=["...","..."]) # untuk drop columns bisa bbrp sekaligus

df.drop(index = ...) # untuk drop rows. bisa bbrp sekaligus, tinggal dibuat list aja

In [486]:
df2.dropna()

W  X    Y    Z
C  5.0  5  7.0  2.0
E  6.0  2  2.0  7.0

In [488]:
df2.dropna(axis=1)

X
A  8
B  2
C  5
D  5
E  2

In [489]:
df2.dropna(axis=0)

W  X    Y    Z
C  5.0  5  7.0  2.0
E  6.0  2  2.0  7.0

In [490]:
df2.dropna(thresh=3) #minimal 3 data yg nilainya ngga NAN

W  X    Y    Z
A  8.0  8  NaN  9.0
B  7.0  2  3.0  NaN
C  5.0  5  7.0  2.0
D  NaN  5  4.0  NaN
E  6.0  2  2.0  7.0

In [492]:
df2.dropna(thresh=4) #minimal 4 data yg nilainya ngga NAN

W  X    Y    Z
C  5.0  5  7.0  2.0
E  6.0  2  2.0  7.0

In [493]:
df2.fillna(value=100) #isi nilai pake 100.

W  X      Y      Z
A    8.0  8  100.0    9.0
B    7.0  2    3.0  100.0
C    5.0  5    7.0    2.0
D  100.0  5    4.0  100.0
E    6.0  2    2.0    7.0

In [495]:
df2.fillna(value = df2.mean()) #isi nilai dari rata2 data

W  X    Y    Z
A  8.0  8  4.0  9.0
B  7.0  2  3.0  6.0
C  5.0  5  7.0  2.0
D  6.5  5  4.0  6.0
E  6.0  2  2.0  7.0

In [496]:
df2.fillna(value = df2["W"].mean()) #isi nilai pake rata2 nilai dari kolom W

W  X    Y    Z
A  8.0  8  6.5  9.0
B  7.0  2  3.0  6.5
C  5.0  5  7.0  2.0
D  6.5  5  4.0  6.5
E  6.0  2  2.0  7.0

# DATA AGGREGATING

In [497]:
dt

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

                                                country          date_added  \
0                                                Brazil     August 14, 2020   
1                                                Mexico   December 23, 2016   
2                                             Singapore   December 20, 2018   
3                                         United States   November 16, 2017   
4                                         United States     January 1, 2020   
...                                                 ...                 ...   
7782  Sweden, Czech Republic, United Kingdom, Denmar...    October 19, 2020   
7783                                              India       March 2, 2019   
7784                                                NaN  September 25, 2020   
7785                                          Australia    October 31, 2020   
7786              United Kingdom, Canada, United States       March 1, 2020   

      release_year rating   duration  \
0             2020  TV-MA  4 Seasons   
1             2016  TV-MA     93 min   
2             2011      R     78 min   
3             2009  PG-13     80 min   
4             2008  PG-13    123 min   
...            ...    ...        ...   
7782          2005  TV-MA     99 min   
7783          2015  TV-14    111 min   
7784          2019  TV-MA     44 min   
7785          2019  TV-PG   1 Season   
7786          2019  TV-MA     90 min   

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...   
1                          Dramas, International Movies   
2                   Horror Movies, International Movies   
3     Action & Adventure, Independent Movies, Sci-Fi...   
4                                                Dramas   
...                                                 ...   
7782                       Dramas, International Movies   
7783     Dramas, International Movies, Music & Musicals   
7784  Documentaries, International Movies, Music & M...   
7785                 International TV Shows, Reality TV   
7786                    Documentaries, Music & Musicals   

                                            description  
0     In a future where the elite inhabit an island ...  
1     After a devast

In [500]:
by_rating = dt.groupby("rating")
by_rating

In [502]:
by_rating.mean()

release_year
rating                
G          1998.410256
NC-17      2015.000000
NR         2010.619048
PG         2008.935223
PG-13      2009.318653
R          2010.601504
TV-14      2013.139824
TV-G       2015.061856
TV-MA      2016.368495
TV-PG      2013.133995
TV-Y       2016.932143
TV-Y7      2015.040590
TV-Y7-FV   2014.833333
UR         2002.400000

In [501]:
by_rating.describe()

release_year                                                   \
                count         mean        std     min      25%     50%   
rating                                                                   
G                39.0  1998.410256  18.039019  1956.0  1990.00  2004.0   
NC-17             3.0  2015.000000   2.645751  2013.0  2013.50  2014.0   
NR               84.0  2010.619048  10.200289  1958.0  2011.00  2014.0   
PG              247.0  2008.935223  10.894722  1973.0  2005.50  2012.0   
PG-13           386.0  2009.318653   9.010211  1955.0  2005.00  2011.0   
R               665.0  2010.601504   9.922698  1962.0  2008.00  2014.0   
TV-14          1931.0  2013.139824   9.938105  1925.0  2012.00  2016.0   
TV-G            194.0  2015.061856   8.327885  1954.0  2015.00  2017.0   
TV-MA          2863.0  2016.368495   5.440300  1945.0  2016.00  2018.0   
TV-PG           806.0  2013.133995  10.757492  1943.0  2013.00  2016.0   
TV-Y            280.0  2016.932143   3.607892  1992.0  2016.00  2018.0   
TV-Y7           271.0  2015.040590   5.798005  1981.0  2013.00  2017.0   
TV-Y7-FV          6.0  2014.833333   2.228602  2012.0  2013.25  2015.0   
UR                5.0  2002.400000  16.318701  1974.0  2007.00  2007.0   

                          
             75%     max  
rating                    
G         2012.5  2020.0  
NC-17     2016.0  2018.0  
NR        2016.0  2018.0  
PG        2017.0  2020.0  
PG-13     2016.0  2020.0  
R         2017.0  2021.0  
TV-14     2018.0  2021.0  
TV-G      2019.0  2021.0  
TV-MA     2019.0  2021.0  
TV-PG     2018.0  2021.0  
TV-Y      2019.0  2021.0  
TV-Y7     2019.0  2021.0  
TV-Y7-FV  2016.0  2018.0  
UR        2008.0  2016.0

In [503]:
by_rating.describe().transpose()

rating                        G        NC-17           NR           PG  \
release_year count    39.000000     3.000000    84.000000   247.000000   
             mean   1998.410256  2015.000000  2010.619048  2008.935223   
             std      18.039019     2.645751    10.200289    10.894722   
             min    1956.000000  2013.000000  1958.000000  1973.000000   
             25%    1990.000000  2013.500000  2011.000000  2005.500000   
             50%    2004.000000  2014.000000  2014.000000  2012.000000   
             75%    2012.500000  2016.000000  2016.000000  2017.000000   
             max    2020.000000  2018.000000  2018.000000  2020.000000   

rating                    PG-13            R        TV-14         TV-G  \
release_year count   386.000000   665.000000  1931.000000   194.000000   
             mean   2009.318653  2010.601504  2013.139824  2015.061856   
             std       9.010211     9.922698     9.938105     8.327885   
             min    1955.000000  1962.000000  1925.000000  1954.000000   
             25%    2005.000000  2008.000000  2012.000000  2015.000000   
             50%    2011.000000  2014.000000  2016.000000  2017.000000   
             75%    2016.000000  2017.000000  2018.000000  2019.000000   
             max    2020.000000  2021.000000  2021.000000  2021.000000   

rating                    TV-MA        TV-PG         TV-Y        TV-Y7  \
release_year count  2863.000000   806.000000   280.000000   271.000000   
             mean   2016.368495  2013.133995  2016.932143  2015.040590   
             std       5.440300    10.757492     3.607892     5.798005   
             min    1945.000000  1943.000000  1992.000000  1981.000000   
             25%    2016.000000  2013.000000  2016.000000  2013.000000   
             50%    2018.000000  2016.000000  2018.000000  2017.000000   
             75%    2019.000000  2018.000000  2019.000000  2019.000000   
             max    2021.000000  2021.000000  2021.000000  2021.000000   

rating                 TV-Y7-FV           UR  
release_year count     6.000000     5.000000  
             mean   2014.833333  2002.400000  
             std       2.228602    16.318701  
             min    2012.000000  1974.000000  
             25%    2013.250000  2007.000000  
             50%    2015.000000  2007.000000  
             75%    2016.000000  2008.000000  
             max    2018.000000  2016.000000

In [505]:
by_rating.describe(exclude="number")

show_id                     type                       title         \
           count unique    top freq count unique      top  freq count unique   
rating                                                                         
G             39     39  s7629    1    39      1    Movie    39    39     39   
NC-17          3      3   s997    1     3      1    Movie     3     3      3   
NR            84     84  s5313    1    84      2    Movie    79    84     84   
PG           247    247  s2993    1   247      1    Movie   247   247    247   
PG-13        386    386   s908    1   386      1    Movie   386   386    386   
R            665    665  s6920    1   665      2    Movie   663   665    665   
TV-14       1931   1931  s6209    1  1931      2    Movie  1272  1931   1931   
TV-G         194    194  s4347    1   194      2    Movie   111   194    194   
TV-MA       2863   2863  s5998    1  2863      2    Movie  1845  2863   2863   
TV-PG        806    806  s3482    1   806      2    Movie   505   806    806   
TV-Y         280    280   s243    1   280      2  TV Show   163   280    280   
TV-Y7        271    271  s5342    1   271      2  TV Show   176   271    271   
TV-Y7-FV       6      6  s4590    1     6      2    Movie     5     6      6   
UR             5      5  s5574    1     5      1    Movie     5     5      5   

          ...   duration      listed_in         \
          ...        top freq     count unique   
rating    ...                                    
G         ...     78 min    7        39     16   
NC-17     ...     83 min    1         3      3   
NR        ...     86 min    6        84     39   
PG        ...     93 min   16       247     72   
PG-13     ...     98 min   15       386    102   
R         ...     94 min   26       665    111   
TV-14     ...   1 Season  470      1931    255   
TV-G      ...   1 Season   49       194     68   
TV-MA     ...   1 Season  690      2863    280   
TV-PG     ...   1 Season  224       806    179   
TV-Y      ...   1 Season   88       280     19   
TV-Y7     ...   1 Season   80       271     30   
TV-Y7-FV  ...  2 Seasons    1         6      3   
UR        ...    103 min    2         5      4   

                                                             description  \
                                                    top freq       count   
rating                                                                     
G                              Children & Family Movies   15          39   
NC-17                      Comedies, Independent Movies    1           3   
NR                                        Documentaries   12          84   
PG                   Children & Family Movies, Comedies   86         247   
PG-13              Action & Adventure, Sci-Fi & Fantasy   28         386   
R                                    Action & Adventure   63         665   
TV-14                      Dramas, International Movies  124        1931   
TV-G                                      Documentaries   18         194   
TV-MA                                   Stand-Up Comedy  275        2863   
TV-PG                                     Documentaries   75         806   
TV-Y                                           Kids' TV  110         280   
TV-Y7                                          Kids' TV   80         271   
TV-Y7-FV             Children & Family Movies, Comedies    4           6   
UR        Dramas, International Movies, Romantic Movies    2           5   

                                                                         
         unique                                                top freq  
rating                                                                   
G            39  Zany Willy Wonka causes a stir when he announc...    1  
NC-17         3  Determined to fall in love, 15-year-old Adele ...    1  
NR           84  This parody of first-person shooter games, mil...    1  
PG          246  When Elastigirl gets recruited for a high-p

In [507]:
by_rating.describe(exclude="number")['duration'] 
#kalo mau nampilin describe, tapi duration aja.

count unique        top freq
rating                               
G           39     25     78 min    7
NC-17        3      3     83 min    1
NR          84     47     86 min    6
PG         247     61     93 min   16
PG-13      386     82     98 min   15
R          665     89     94 min   26
TV-14     1931    172   1 Season  470
TV-G       194     70   1 Season   49
TV-MA     2863    155   1 Season  690
TV-PG      806    147   1 Season  224
TV-Y       280     55   1 Season   88
TV-Y7      271     59   1 Season   80
TV-Y7-FV     6      6  2 Seasons    1
UR           5      4    103 min    2

In [508]:
by_rating.describe(exclude="number")['duration'].loc["R"] 
#kalo mau nampilin describe, tapi duration aja.

count        665
unique        89
top       94 min
freq          26
Name: R, dtype: object

In [510]:
by_rating.describe(exclude="number")['duration'].loc["R"].loc["top"]

'94 min'

# MERGING, JOINING, AND CONCATENATING

In [ ]:
Merging : 
Inner Join
Full Outer Join
Right Outer Join
Left Outer Join

In [511]:
left = pd.DataFrame({'key':['K0','K1','K2','K3'], 
'A': [1,2,3,4,],
'B' : [5,6,7,8]})
left

key  A  B
0  K0  1  5
1  K1  2  6
2  K2  3  7
3  K3  4  8

In [512]:
right = pd.DataFrame({'key':['K4','K1','K2','K3','K5'], 'C': [10,20,30,40,50],
'D' : [20,60,70,80,90],
'E' : [15,25,35,45,55]})
right

key   C   D   E
0  K4  10  20  15
1  K1  20  60  25
2  K2  30  70  35
3  K3  40  80  45
4  K5  50  90  55

In [515]:
pd.merge(left,right,on="key")
#by default = inner join

key  A  B   C   D   E
0  K1  2  6  20  60  25
1  K2  3  7  30  70  35
2  K3  4  8  40  80  45

In [514]:
pd.merge(left,right,how="outer",on="key")

key    A    B     C     D     E
0  K0  1.0  5.0   NaN   NaN   NaN
1  K1  2.0  6.0  20.0  60.0  25.0
2  K2  3.0  7.0  30.0  70.0  35.0
3  K3  4.0  8.0  40.0  80.0  45.0
4  K4  NaN  NaN  10.0  20.0  15.0
5  K5  NaN  NaN  50.0  90.0  55.0

In [516]:
pd.merge(left,right,how="right",on="key")

key    A    B   C   D   E
0  K4  NaN  NaN  10  20  15
1  K1  2.0  6.0  20  60  25
2  K2  3.0  7.0  30  70  35
3  K3  4.0  8.0  40  80  45
4  K5  NaN  NaN  50  90  55

In [517]:
pd.merge(left,right,how="left",on="key")

key  A  B     C     D     E
0  K0  1  5   NaN   NaN   NaN
1  K1  2  6  20.0  60.0  25.0
2  K2  3  7  30.0  70.0  35.0
3  K3  4  8  40.0  80.0  45.0

In [523]:
left2 = left.drop("key",axis=1)
left2

A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [524]:
right2 = right.drop("key",axis=1)
right2

C   D   E
0  10  20  15
1  20  60  25
2  30  70  35
3  40  80  45
4  50  90  55

In [525]:
left2.join(right2)

A  B   C   D   E
0  1  5  10  20  15
1  2  6  20  60  25
2  3  7  30  70  35
3  4  8  40  80  45

In [527]:
left2.join(right2,how="outer")

A    B   C   D   E
0  1.0  5.0  10  20  15
1  2.0  6.0  20  60  25
2  3.0  7.0  30  70  35
3  4.0  8.0  40  80  45
4  NaN  NaN  50  90  55

In [528]:
pd.concat([left,right,left2,right2])

key    A    B     C     D     E
0   K0  1.0  5.0   NaN   NaN   NaN
1   K1  2.0  6.0   NaN   NaN   NaN
2   K2  3.0  7.0   NaN   NaN   NaN
3   K3  4.0  8.0   NaN   NaN   NaN
0   K4  NaN  NaN  10.0  20.0  15.0
1   K1  NaN  NaN  20.0  60.0  25.0
2   K2  NaN  NaN  30.0  70.0  35.0
3   K3  NaN  NaN  40.0  80.0  45.0
4   K5  NaN  NaN  50.0  90.0  55.0
0  NaN  1.0  5.0   NaN   NaN   NaN
1  NaN  2.0  6.0   NaN   NaN   NaN
2  NaN  3.0  7.0   NaN   NaN   NaN
3  NaN  4.0  8.0   NaN   NaN   NaN
0  NaN  NaN  NaN  10.0  20.0  15.0
1  NaN  NaN  NaN  20.0  60.0  25.0
2  NaN  NaN  NaN  30.0  70.0  35.0
3  NaN  NaN  NaN  40.0  80.0  45.0
4  NaN  NaN  NaN  50.0  90.0  55.0

In [529]:
pd.concat([left,right,left2,right2],axis=1)

key    A    B key   C   D   E    A    B   C   D   E
0   K0  1.0  5.0  K4  10  20  15  1.0  5.0  10  20  15
1   K1  2.0  6.0  K1  20  60  25  2.0  6.0  20  60  25
2   K2  3.0  7.0  K2  30  70  35  3.0  7.0  30  70  35
3   K3  4.0  8.0  K3  40  80  45  4.0  8.0  40  80  45
4  NaN  NaN  NaN  K5  50  90  55  NaN  NaN  50  90  55

# APPLYING FUNCTIONS

Apply biasa bisa untuk df or series


Applymap hanya untuk df. akan di apply to each individual value

(df.applymap(len))


In [547]:
dt4 = {'first':['corey','jane','john'],
'last':['schafer','doe','smith'],
'email':['CoreySchafer@gmail.com','JaneDoe@gmail.com','JohnSmith@gmail.com']}
dt5 = pd.DataFrame(dt4)
dt5

first     last                   email
0  corey  schafer  CoreySchafer@gmail.com
1   jane      doe       JaneDoe@gmail.com
2   john    smith     JohnSmith@gmail.com

In [548]:
dt5['first'].map({'corey':'chris','jane':'mary'})
#hasil jadi nan krn map apply ke semuanya

0    chris
1     mary
2      NaN
Name: first, dtype: object

In [549]:
dt5['first'].replace({'corey':'chris','jane':'mary'})
#kalo gamau semua, pake replace aja

0    chris
1     mary
2     john
Name: first, dtype: object

In [552]:
dt5.append({'first':'Tony'})

TypeError: Can only append a dict if ignore_index=True

In [551]:
dt5.append({'first':'Tony'},ignore_index = True)
#harus pake ignore_index jd yg lainnya diisi NaN

first     last                   email
0  corey  schafer  CoreySchafer@gmail.com
1   jane      doe       JaneDoe@gmail.com
2   john    smith     JohnSmith@gmail.com
3   Tony      NaN                     NaN

In [530]:
def kali (x):
    return x*2

In [531]:
left["A"].apply(kali)
#bisa juga di apply len kalo object. jd nampilin panjang kata

0    2
1    4
2    6
3    8
Name: A, dtype: int64

In [533]:
left.apply(len)

key    4
A      4
B      4
dtype: int64

In [534]:
len(left["A"])

4

In [535]:
left["A"].apply(lambda x : x*2)

0    2
1    4
2    6
3    8
Name: A, dtype: int64

In [536]:
left.apply(lambda x : len(x))

key    4
A      4
B      4
dtype: int64

# PIVOT TABLE

In [541]:
dt2 = {'A': ['foo','foo','foo','bar','bar','bar'],
'B':['one','one','two','two','one','one'],
'C':['x','y','x','y','x','y'],
'D':[1,2,3,4,5,6]}
dt3 = pd.DataFrame(dt2)
dt3

A    B  C  D
0  foo  one  x  1
1  foo  one  y  2
2  foo  two  x  3
3  bar  two  y  4
4  bar  one  x  5
5  bar  one  y  6

In [543]:
dt3.pivot_table(values="D",index = ["A","B"],columns=["C"])

C          x    y
A   B            
bar one  5.0  6.0
    two  NaN  4.0
foo one  1.0  2.0
    two  3.0  NaN

# INPUT & OUTPUT

In [ ]:
INPUT : 

df = pd.read_csv("nama file.csv")
bisa juga u/ JSON, HTML, EXCEL

pd.set_option("display.max_column",<nilai max column>)
u/ dpt <nilai max column> 
pd.set_option("display.max_rows",<nilai max rows>)

kalo mau nampilin bbrp kolom aja yg diambil : 
df.[['kol1','kol2']]

OUTPUT : 

df.to_csv("namafile.csv", index = False)
index = False, kalo gamau indexnya di save juga


# STRING FUNCTION & ADDITIONAL

.isin

.str.contains("...")

.str.replace("a"," ")

df.at (untuk single value)
