In [4]:
import pandas as pd 
import numpy as np

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
listku = [1,2,3,4,5]
# listku = [1,2,3,4,5]+1 error
listku

[1, 2, 3, 4, 5]

In [8]:
np.array(listku) #1d array
np.array(listku) +1

array([2, 3, 4, 5, 6])

Array 2D

In [11]:
list2d = [[1,2,3],[4,5,6],[7,8,9]]
list2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(list2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#List 3D

In [14]:
list3d = [[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[8,7,6],[6,5,4]] ]
list3d

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[9, 8, 7], [8, 7, 6], [6, 5, 4]]]

In [15]:
np.array(list3d)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [8, 7, 6],
        [6, 5, 4]]])

#Numpy Arange

In [18]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
B = np.arange(1,21,2) #start, stop,step
B

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [21]:
for i in np.arange(20):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
- range(start,stop,step) = menghasilkan list
- arange(start,stop,step) = menghasilkan array

#Numpy Zero & Ones & Eye # dipakai untuk aljabar linear

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((10,10))*10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.array(list2d) * np.eye(3)

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

#linspace

In [42]:
np.linspace(0,30,11)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [44]:
#Random

In [45]:
np.random.rand(5) #dr 0-1 sebanyak 5

array([0.75948634, 0.05959321, 0.04916331, 0.25389959, 0.49592665])

In [46]:
np.random.rand(5,5)

array([[0.66521143, 0.37917664, 0.40604053, 0.99233629, 0.09487474],
       [0.32818661, 0.47235221, 0.46324047, 0.90393724, 0.76557608],
       [0.73975501, 0.20734341, 0.79280842, 0.66820426, 0.01579223],
       [0.14863212, 0.85397956, 0.32027772, 0.37449111, 0.51917108],
       [0.12933775, 0.45386832, 0.48760071, 0.49031438, 0.45995524]])

In [50]:
np.random.randint(1,8,5)

array([6, 6, 4, 5, 1])

In [51]:
np.random.rand(5,8)

array([[0.35575619, 0.97957934, 0.03288941, 0.07509171, 0.26158108,
        0.72483882, 0.65698728, 0.11036397],
       [0.55829548, 0.64270401, 0.54770999, 0.37638499, 0.89764063,
        0.97109193, 0.58714984, 0.67652363],
       [0.21431831, 0.46278073, 0.43191832, 0.10761972, 0.50045171,
        0.01874511, 0.28656599, 0.23800254],
       [0.92944404, 0.82776061, 0.27465337, 0.50513902, 0.57349762,
        0.63822561, 0.02491103, 0.25048474],
       [0.05978957, 0.79867772, 0.92018243, 0.19012562, 0.96418972,
        0.57601792, 0.07146974, 0.99034591]])

In [52]:
np.random.randn(10,10) #distribusi normal, jd ada nilai minus

array([[-0.3999784 ,  0.47644051, -0.87852385,  1.47990011, -0.85105441,
         0.50242496, -1.26636526,  0.39078904, -0.23532976, -0.80534591],
       [ 1.76215867,  0.18651218,  1.82988601,  0.98887709,  0.28779127,
         0.42136319, -0.29652134, -0.36951067,  0.21045991, -0.70754427],
       [ 0.85486924,  0.03656177,  0.15959092, -1.47508807,  0.20254636,
        -0.9383827 ,  0.39381605,  0.39322275,  0.40130272,  0.88032873],
       [ 1.06218586, -2.35802221, -1.26017763,  1.33474076,  0.06981333,
         0.18038138, -0.19657303,  0.10126628, -0.93532586,  0.92092391],
       [ 0.69167201, -1.44146519,  0.7501725 , -1.45040154, -0.71558018,
         0.936177  , -1.43834085,  0.847715  ,  1.53432123,  0.65249912],
       [ 0.23001783,  0.61340894,  1.28169318,  0.03499149, -0.1548523 ,
         0.73393256, -0.13032029, -0.86052574, -0.31117871,  0.96487694],
       [-0.23317779,  0.22571268,  0.74331742,  0.80225218,  0.74596424,
         0.37110877, -0.68093646,  0.49606701

1. Bisa / tidak dibuat array dr list yg isinya : 
    - float semua
    - integer semua
    - boolean semua
    - float + integer
    - string
    - string + float

2. coba buat sebuah matrix yg berisikan angka dr hasil dari ((1/2*100+1.5)^1/2)
3. kalikan hasil pada nomor 2 pada matrix identitas. Apakah hasilnya sama? Jika tidak jelaskan kenapa
4. Bangkitkan dara random dari 0 sampai 1 sebanyak 100 yang terbentuk menjadi matrix namun bukan matrix (nxn) melainkan (mxn)
5. Apakah bisa dibangkitkan nilai random integer dari rentang 0.5 hingga 100? Jika ya coba lakukan
6. Bangkitkan data integer sebanyak x (inputan) dari n (inputan) hingga m (inputan)

In [53]:
np.linspace(0,5,10) #float semua

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [58]:
a = [1,2,1.2,1.3] #float semua
np.array(a)

array([1. , 2. , 1.2, 1.3])

In [54]:
np.random.randint(1,10,10) #integer semua

array([1, 8, 4, 5, 8, 5, 4, 7, 3, 8])

In [92]:
a = [1,2,3] #integer semua
np.array(a)

array([1, 2, 3])

In [57]:
a = [True, False, True] #boolean semua
np.array(a)

array([ True, False,  True])

In [56]:
np.linspace(1,5,6) #tidak bisa float + integer tp float smua

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [59]:
a = ["a","b","c"] #string
np.array(a)

array(['a', 'b', 'c'], dtype='<U1')

In [60]:
a = ["a","b",1.2,1.3] #string + float
np.array(a)

array(['a', 'b', '1.2', '1.3'], dtype='<U32')

In [102]:
np.ones((5,5)) * np.array((1/2*100+1.5)**1/2)


array([[25.75, 25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75, 25.75]])

In [105]:
a = np.ones((5,5)) * np.array((1/2*100+1.5)**1/2)
a * np.eye(5) 

array([[25.75,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , 25.75,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  , 25.75,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 25.75,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 25.75]])

In [109]:
np.random.rand(25,4)

array([[0.4096787 , 0.27841482, 0.33719373, 0.16578588],
       [0.77540878, 0.76944694, 0.18105585, 0.50476032],
       [0.22330688, 0.64773936, 0.14164583, 0.77490687],
       [0.51811415, 0.75156862, 0.99331896, 0.33882061],
       [0.05150534, 0.17372296, 0.1844329 , 0.21095732],
       [0.91806836, 0.29309613, 0.76820098, 0.77491029],
       [0.19976415, 0.75969441, 0.47777716, 0.20386156],
       [0.02766828, 0.3359717 , 0.68030632, 0.4876281 ],
       [0.79361955, 0.96203493, 0.24821055, 0.08936179],
       [0.7184989 , 0.4543376 , 0.66039936, 0.09463213],
       [0.87018067, 0.51525988, 0.79110719, 0.33801904],
       [0.20014603, 0.24808303, 0.22226256, 0.26949534],
       [0.67406594, 0.53867295, 0.29908647, 0.73084514],
       [0.1262633 , 0.13001383, 0.70558623, 0.24215347],
       [0.0603772 , 0.71665042, 0.78487265, 0.687241  ],
       [0.52064502, 0.07453536, 0.35599105, 0.21782956],
       [0.56416865, 0.67024057, 0.24817677, 0.49119646],
       [0.90388742, 0.54148729,

In [112]:
np.random.randint(0.5,2)

1

In [117]:
n = int(input("Masukan n :"))
x = int(input("Masukan x :"))
m = int(input("Masukan m :"))
np.random.randint(x,m,n)
# np.random.randint(1,10,8)

array([3, 2, 3])

In [131]:
A = np.random.randint(1,100,50)

In [126]:
A.shape

(50,)

In [133]:
Z = A.reshape(2,25)
Z

array([[23,  4, 29, 61, 92, 81, 32, 42, 26, 62, 42,  9, 80, 19, 16, 43,
        96, 28,  9,  9, 21,  2, 90, 91, 85],
       [97, 16, 84,  4, 28, 11, 65, 92, 93, 84, 78, 97,  9, 47, 10, 62,
        49,  8, 95, 97,  7, 76, 80, 36, 94]])

In [130]:
Z.reshape(50)

array([61, 32, 55, 27, 26, 87, 10, 45, 56, 67, 86, 76, 31, 62, 29, 36, 77,
       93, 83, 54, 88, 53, 93, 81, 42, 39,  8, 56, 62, 62, 18, 11, 93, 85,
       98, 13, 81, 52, 56,  2, 93, 36,  7, 10, 58, 77, 59, 21, 38, 61])

#Max Min ArgMax ArgMin

In [134]:
A = np.random.randint(1,100,100)
A

array([85, 24, 78, 71, 86, 80, 43, 17, 84, 64, 45, 63,  7, 38, 20, 31, 79,
       27, 63, 19, 69, 50, 10, 15, 21, 54, 36, 82, 13, 71, 76, 38, 50, 75,
       56,  8, 73, 61, 60, 54, 13, 69, 59, 50, 85, 21, 60, 64, 48, 35,  8,
       49, 97, 16, 59, 98, 91, 63, 15, 55, 45, 41, 84, 71, 73, 55, 52, 90,
       20, 64, 12, 84,  3, 37, 46, 18, 10, 99, 54, 26,  1, 25, 80, 12, 35,
       82, 47, 25, 27, 15, 32, 22, 76, 75, 20, 39, 41, 67, 26, 13])

In [135]:
max(A)

99

In [136]:
A.max()

99

In [137]:
A.argmax() #untuk tau indexnya dmn kalau duplicate, diambilnya yg pertama

77

In [138]:
A.min()

1

#indexing

In [139]:
A[40:-1]

array([13, 69, 59, 50, 85, 21, 60, 64, 48, 35,  8, 49, 97, 16, 59, 98, 91,
       63, 15, 55, 45, 41, 84, 71, 73, 55, 52, 90, 20, 64, 12, 84,  3, 37,
       46, 18, 10, 99, 54, 26,  1, 25, 80, 12, 35, 82, 47, 25, 27, 15, 32,
       22, 76, 75, 20, 39, 41, 67, 26])

In [140]:
A[[20,30,40]]

array([69, 76, 13])

In [141]:
A[25:]=0 #untuk ganti

In [142]:
A

array([85, 24, 78, 71, 86, 80, 43, 17, 84, 64, 45, 63,  7, 38, 20, 31, 79,
       27, 63, 19, 69, 50, 10, 15, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

#index 2d

In [143]:
A = np.random.randint(1,100,50)
coba2 = A.reshape(10,5)
coba2

array([[91,  8, 75, 80, 67],
       [71, 46, 67, 38, 54],
       [87, 38, 97,  1, 91],
       [80, 14, 33, 60, 88],
       [ 5, 15, 53,  2, 97],
       [24, 60, 76, 67, 97],
       [84, 63, 66, 64, 27],
       [25,  1, 92, 34, 68],
       [35, 26, 20, 70, 47],
       [64, 77, 53, 11, 16]])

In [144]:
coba2[5] #yg keluar index ke 5

array([24, 60, 76, 67, 97])

In [145]:
coba2[2,3]

1

In [147]:
coba2[-3,2]

92

In [148]:
coba2 [7:10,2:]

array([[92, 34, 68],
       [20, 70, 47],
       [53, 11, 16]])

In [149]:
coba2[:,2:4]

array([[75, 80],
       [67, 38],
       [97,  1],
       [33, 60],
       [53,  2],
       [76, 67],
       [66, 64],
       [92, 34],
       [20, 70],
       [53, 11]])

In [150]:
coba2[2:,[2,3]]

array([[97,  1],
       [33, 60],
       [53,  2],
       [76, 67],
       [66, 64],
       [92, 34],
       [20, 70],
       [53, 11]])

In [155]:
coba2[:,2:4]

array([[75, 80],
       [67, 38],
       [97,  1],
       [33, 60],
       [53,  2],
       [76, 67],
       [66, 64],
       [92, 34],
       [20, 70],
       [53, 11]])

In [153]:
coba2[:2,3]

array([80, 38])

CONDITIONAL SELECTION

In [156]:
A

array([91,  8, 75, 80, 67, 71, 46, 67, 38, 54, 87, 38, 97,  1, 91, 80, 14,
       33, 60, 88,  5, 15, 53,  2, 97, 24, 60, 76, 67, 97, 84, 63, 66, 64,
       27, 25,  1, 92, 34, 68, 35, 26, 20, 70, 47, 64, 77, 53, 11, 16])

In [157]:
A >50

array([ True, False,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True, False,  True,  True, False, False,
        True,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False, False])

In [158]:
A[A>50]

array([91, 75, 80, 67, 71, 67, 54, 87, 97, 91, 80, 60, 88, 53, 97, 60, 76,
       67, 97, 84, 63, 66, 64, 92, 68, 70, 64, 77, 53])

In [169]:
A [ (A > 50) & (A<70)]

array([67, 67, 54, 60, 53, 60, 67, 63, 66, 64, 68, 64, 53])

In [170]:
import mysql.connector
import pandas as pd

In [172]:
mydb = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '1234',
    database = 'world'
)

In [173]:
mycursor = mydb.cursor()

def query(x):
    mycursor.execute(x)
    result = mycursor.fetchall()
    df = pd.DataFrame(result,columns = mycursor.column_names)
    return df

In [174]:
query("""
    select * from city limit 10
""")

ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200
5   6       Rotterdam         NLD   Zuid-Holland      593321
6   7            Haag         NLD   Zuid-Holland      440900
7   8         Utrecht         NLD        Utrecht      234323
8   9       Eindhoven         NLD  Noord-Brabant      201843
9  10         Tilburg         NLD  Noord-Brabant      193238