# Soal 1

In [3]:
import numpy as np

In [4]:
#ANSWER
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Buat sebuah variable array 1 dimensi, lalu coba konversikan ke dalam bentuk 2 dimensi

#ANSWER
D1 = np.arange(10).reshape(2,5)
D1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
#reshape merubah struktur dari array numpy menjadi (row, column) yang diinginkan. 
#Jika kita menulis -1 berarti numpy array akan secara otomatis menyesuaikan jumlah row atau column nya



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
#ANSWER
D1.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Soal 2

In [8]:
#ANSWER
D2_1 = np.arange(4,13).reshape(3,3)
D2_1

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
#Indexing menggunakan [row, column] bisa menjadi berlipat jika kita memasukkan index yang sama di dalam list row atau column
#yang diinginkan

arr[:,[1,2,0,0,1,2,1]]

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

In [11]:
#ANSWER
D2_2 = D2_1[:,[1,2,0,0,1,2,1,1]]
D2_2


array([[ 5,  6,  4,  4,  5,  6,  5,  5],
       [ 8,  9,  7,  7,  8,  9,  8,  8],
       [11, 12, 10, 10, 11, 12, 11, 11]])

## Soal 3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
#ANSWER
D3_1 = np.arange(9).reshape(3,3)
D3_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
#Sama seperti indexing pada saat di list, bisa menggunakan ::-1 untuk melakukan reverse baik di tingkat row ataupun column


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [16]:
#ANSWER
D3_1[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## Soal 4

In [44]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [4]:
#ANSWER
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

<ipython-input-4-6fe6835431d3>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# arr = np.array([i for ar in array_of_arrays for i in ar])
# coba gunakan for untuk membuat output dibawah ini



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#ANSWER
arr = np.array([ i for ar in array_of_arrays for i in ar])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])