1. Buatlah 1 array 2 dimensi, 1 array 1 dimensi

In [1]:
import numpy as np

In [15]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

2. Buat sebuah variabel baru dimana nilainya adalah pangkat dari array1**array2 yg dibuat sebelumnya
3. buatlah array ketiga yg berisikan bilangan bulat random dr 1 hingga 10, dimensi bebas
4. buat sebuah variabel baru yg merupakan gabungan dr hasil perkalian array pada no 2 digabungkan dengan array pada no 1

In [19]:
arr3 = arr1 **arr2
arr3

array([[    1,     4,    27,   256],
       [    5,    36,   343,  4096],
       [    9,   100,  1331, 20736]], dtype=int32)

In [12]:
arr4 = np.random.randint(1,10,size=(3,3))
arr4

array([[1, 5, 7],
       [5, 4, 1],
       [6, 1, 2]])

In [21]:
#NO 4
arr5 = arr3 * arr1
arr5


array([[     1,      8,     81,   1024],
       [    25,    216,   2401,  32768],
       [    81,   1000,  14641, 248832]])

5. coba ubah nilai dari final array tsb dgn kondisi 
- jika ada nilai yang <10 maka diubah menjadi nilai yg <10 dipangkatkan dgn 0
- jika ada nilai yg >10 dan <20 maka nilainya tetap
- jika ada nilai yang > 20 maka nilainya adalah akar dari nilai tsb

In [44]:
# arr6 = np.where(arr5 < 10,arr5**0,arr5)
# arr6 = np.where(arr5 < 10,arr5**0,arr5)
# arr6 = np.where((arr5 > 20,arr5**0.5,arr5) & (arr5 < 10,arr5**0,arr5))
arr6 = np.where(arr5 < 10,arr5**0,(np.where(arr5 <20,arr5,arr5**0.5)))
arr6

(array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1,
        2, 2, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
        0, 1, 2, 3], dtype=int64))

In [46]:
arr5

array([[     1,      8,     81,   1024],
       [    25,    216,   2401,  32768],
       [    81,   1000,  14641, 248832]])

In [58]:


arr6 = np.where((arr5 > 10) & (arr5 <20), arr5, 0 )
arr5
arr6

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])